import { API_BASE_URL } from '../../config/api';
import React, { useState, useEffect } from 'react';
import { Users, MapPin, Clock, Search, ShieldCheck, LogIn, LogOut, Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function AttendanceLogs() {
  const [logs, setLogs] = useState([]);
  const [search, setSearch] = useState('');

  const [selectedStaff, setSelectedStaff] = useState(null);
  
  // Detail View Filters
  const [filterMode, setFilterMode] = useState('7DAYS'); // TODAY, 7DAYS, 1MONTH

  // Global Dashboard Filters
  const [globalFilterMode, setGlobalFilterMode] = useState('TODAY'); // TODAY, 7DAYS, 1MONTH, CUSTOM
  const todayStr = new Date().toISOString().split('T')[0];
  const [customStartDate, setCustomStartDate] = useState(todayStr);
  const [customEndDate, setCustomEndDate] = useState(todayStr);

  useEffect(() => {
    fetch(`${API_BASE_URL}/api/attendance`)
      .then(res => res.json())
      .then(data => setLogs(data))
      .catch(err => console.error("Error fetching attendance logs:", err));
  }, []);

  const getFilteredGlobalLogs = () => {
    const now = new Date();
    const startCustom = customStartDate ? new Date(customStartDate) : new Date();
    startCustom.setHours(0, 0, 0, 0);
    const endCustom = customEndDate ? new Date(customEndDate) : new Date();
    endCustom.setHours(23, 59, 59, 999);

    return logs.filter(log => {
      const logDate = new Date(log.timestamp);
      if (globalFilterMode === 'TODAY') {
        return logDate.toDateString() === now.toDateString();
      } else if (globalFilterMode === '7DAYS') {
        const diffTime = Math.abs(now - logDate);
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
        return diffDays <= 7;
      } else if (globalFilterMode === '1MONTH') {
        const diffTime = Math.abs(now - logDate);
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
        return diffDays <= 30;
      } else if (globalFilterMode === 'CUSTOM') {
        return logDate >= startCustom && logDate <= endCustom;
      }
      return true;
    });
  };

  const filteredGlobalLogs = getFilteredGlobalLogs();

  const staffGroups = {};
  filteredGlobalLogs.forEach(log => {
    if (!staffGroups[log.id]) {
      staffGroups[log.id] = { id: log.id, name: log.name, logs: [] };
    }
    staffGroups[log.id].logs.push(log);
  });
  
  const staffList = Object.values(staffGroups).filter(staff => 
    staff.name.toLowerCase().includes(search.toLowerCase()) || 
    staff.id.toLowerCase().includes(search.toLowerCase())
  );

  const handleExportPDF = () => {
    if (filteredGlobalLogs.length === 0) return alert("No logs to export for this period.");
    
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Attendance Report", 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Period: ${globalFilterMode} ${globalFilterMode === 'CUSTOM' ? `(${customStartDate} to ${customEndDate})` : ''}`, 14, 30);
    
    const tableData = filteredGlobalLogs.map(log => [
      new Date(log.timestamp).toLocaleString(),
      log.name,
      log.id,
      log.attendanceType || 'Clock-In',
      `${log.lat}, ${log.lng}`
    ]);

    doc.autoTable({
      startY: 40,
      head: [['Date & Time', 'Staff Name', 'Staff ID', 'Type', 'Location (Lat, Lng)']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [3, 70, 200] },
      styles: { fontSize: 9 }
    });

    const finalY = doc.lastAutoTable.finalY || 40;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("This report generated by mstechhive for GCR admin only", 14, finalY + 15);
    
    doc.save(`Attendance_Report_${globalFilterMode}.pdf`);
  };

  const handleExportExcel = () => {
    if (filteredGlobalLogs.length === 0) return alert("No logs to export for this period.");
    
    const headers = ["Date & Time", "Staff Name", "Staff ID", "Type", "Location (Lat, Lng)"];
    const rows = filteredGlobalLogs.map(log => [
      `"${new Date(log.timestamp).toLocaleString()}"`,
      `"${log.name}"`,
      `"${log.id}"`,
      `"${log.attendanceType || 'Clock-In'}"`,
      `"${log.lat}, ${log.lng}"`
    ]);
    
    // Add custom branding row at the end
    rows.push([]);
    rows.push(['"This report generated by mstechhive for GCR admin only"']);

    const csvContent = [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `Attendance_Report_${globalFilterMode}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const getFilteredLogs = () => {
    if (!selectedStaff) return [];
    const now = new Date();
    return selectedStaff.logs.filter(log => {
      const logDate = new Date(log.timestamp);
      if (filterMode === 'TODAY') {
        return logDate.toDateString() === now.toDateString();
      } else if (filterMode === '7DAYS') {
        const diffTime = Math.abs(now - logDate);
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
        return diffDays <= 7;
      } else if (filterMode === '1MONTH') {
        const diffTime = Math.abs(now - logDate);
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
        return diffDays <= 30;
      }
      return true;
    });
  };

  if (selectedStaff) {
    const displayLogs = getFilteredLogs();
    return (
      <div className="admin-logs-view animate-fade-in" style={{ paddingBottom: '80px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px' }}>
          <button 
            onClick={() => setSelectedStaff(null)} 
            style={{ background: '#f1f5f9', border: 'none', padding: '8px 12px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center' }}
          >
            <span style={{ fontSize: '14px', fontWeight: '600' }}>← Back</span>
          </button>
          <div>
            <h1 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>{selectedStaff.name}</h1>
            <p className="text-muted" style={{ fontSize: '13px', margin: 0 }}>ID: {selectedStaff.id}</p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '8px', marginBottom: '24px' }}>
          {['TODAY', '7DAYS', '1MONTH'].map(mode => (
            <button 
              key={mode}
              onClick={() => setFilterMode(mode)}
              style={{ 
                flex: 1, 
                padding: '10px', 
                border: 'none', 
                borderRadius: '8px', 
                fontSize: '13px', 
                fontWeight: '600',
                backgroundColor: filterMode === mode ? '#0346c8' : '#f1f5f9',
                color: filterMode === mode ? 'white' : '#475569',
                cursor: 'pointer'
              }}
            >
              {mode === 'TODAY' ? 'Today' : mode === '7DAYS' ? '7 Days' : '1 Month'}
            </button>
          ))}
        </div>

        {displayLogs.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>No logs found for this period.</div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {displayLogs.map(log => (
              <div key={log._id || Math.random()} className="native-card" style={{ padding: '0', overflow: 'hidden' }}>
                <div style={{ padding: '16px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-secondary)', fontSize: '13px', fontWeight: '600' }}>
                    <Clock size={14} />
                    <span>{new Date(log.timestamp).toLocaleString()}</span>
                  </div>
                  <span style={{ 
                    fontSize: '12px', fontWeight: '700', 
                    color: log.attendanceType === 'Clock-In' ? 'var(--primary)' : '#e11d48',
                    backgroundColor: log.attendanceType === 'Clock-In' ? '#e0f2fe' : '#ffe4e6',
                    padding: '4px 8px', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '4px'
                  }}>
                    {log.attendanceType === 'Clock-In' ? <LogIn size={12}/> : <LogOut size={12}/>} 
                    {log.attendanceType || 'Clock-In'}
                  </span>
                </div>
                <div style={{ width: '100%', height: '240px', backgroundColor: '#000' }}>
                  <img src={log.imageUrl} alt="Geotagged Selfie" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
                <div style={{ padding: '16px', backgroundColor: '#f8fafc', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-secondary)', fontSize: '13px' }}>
                  <MapPin size={14} />
                  <span>Lat: {log.lat}, Lng: {log.lng}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="admin-logs-view animate-fade-in" style={{ paddingBottom: '80px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px' }}>
        <div style={{ width: '40px', height: '40px', borderRadius: '8px', backgroundColor: '#fef3c7', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#f59e0b' }}>
          <ShieldCheck size={24} />
        </div>
        <div>
          <h1 style={{ fontSize: '22px', fontWeight: '700', margin: 0 }}>Attendance Dashboard</h1>
          <p className="text-muted" style={{ fontSize: '13px', margin: 0 }}>Staff Tracking & Logs</p>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '24px' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
          {['TODAY', '7DAYS', '1MONTH', 'CUSTOM'].map(mode => (
            <button 
              key={mode}
              onClick={() => setGlobalFilterMode(mode)}
              style={{ 
                flex: 1, 
                padding: '10px', 
                border: 'none', 
                borderRadius: '8px', 
                fontSize: '12px', 
                fontWeight: '600',
                backgroundColor: globalFilterMode === mode ? '#0346c8' : '#f1f5f9',
                color: globalFilterMode === mode ? 'white' : '#475569',
                cursor: 'pointer',
                minWidth: '60px'
              }}
            >
              {mode === 'TODAY' ? 'Today' : mode === '7DAYS' ? '7 Days' : mode === '1MONTH' ? '1 Month' : 'Custom'}
            </button>
          ))}
        </div>

        {globalFilterMode === 'CUSTOM' && (
          <div style={{ display: 'flex', gap: '12px', backgroundColor: '#f8fafc', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
            <div style={{ flex: 1 }}>
              <label style={{ display: 'block', fontSize: '11px', fontWeight: '600', color: '#64748b', marginBottom: '4px' }}>START DATE</label>
              <input type="date" value={customStartDate} onChange={e => setCustomStartDate(e.target.value)} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '13px' }} />
            </div>
            <div style={{ flex: 1 }}>
              <label style={{ display: 'block', fontSize: '11px', fontWeight: '600', color: '#64748b', marginBottom: '4px' }}>END DATE</label>
              <input type="date" value={customEndDate} onChange={e => setCustomEndDate(e.target.value)} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '13px' }} />
            </div>
          </div>
        )}

        <div style={{ display: 'flex', gap: '12px', marginTop: '4px' }}>
          <button onClick={handleExportPDF} style={{ flex: 1, padding: '12px', borderRadius: '8px', border: 'none', background: '#fee2e2', color: '#dc2626', fontWeight: '600', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', cursor: 'pointer' }}>
            <FileText size={16} /> Export PDF
          </button>
          <button onClick={handleExportExcel} style={{ flex: 1, padding: '12px', borderRadius: '8px', border: 'none', background: '#dcfce7', color: '#16a34a', fontWeight: '600', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', cursor: 'pointer' }}>
            <Download size={16} /> Export Excel
          </button>
        </div>
      </div>

      <div style={{ position: 'relative', marginBottom: '24px' }}>
        <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
        <input 
          type="text" 
          placeholder="Search engineer name or ID..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          style={{ width: '100%', padding: '12px 12px 12px 36px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)', fontSize: '14px', outline: 'none' }}
        />
      </div>

      {staffList.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '40px 20px', backgroundColor: '#fff', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
          <Users size={40} color="var(--border-color)" style={{ margin: '0 auto 16px' }} />
          <h3 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '8px' }}>No Staff Records</h3>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {staffList.map(staff => (
            <div 
              key={staff.id} 
              onClick={() => setSelectedStaff(staff)}
              style={{ 
                padding: '16px', backgroundColor: 'white', borderRadius: '12px', 
                border: '1px solid #e2e8f0', boxShadow: '0 2px 4px rgba(0,0,0,0.02)',
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                cursor: 'pointer'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                <div style={{ width: '48px', height: '48px', borderRadius: '24px', backgroundColor: '#e0e7ff', color: '#4338ca', display: 'flex', justifyContent: 'center', alignItems: 'center', fontWeight: '700', fontSize: '16px' }}>
                  {staff.name.substring(0, 2).toUpperCase()}
                </div>
                <div>
                  <div style={{ fontWeight: '700', fontSize: '16px', color: '#0f172a' }}>{staff.name}</div>
                  <div style={{ fontSize: '13px', color: '#64748b' }}>ID: {staff.id}</div>
                  <div style={{ fontSize: '12px', color: '#10b981', fontWeight: '600', marginTop: '4px' }}>
                    {staff.logs.length} Total Logs
                  </div>
                </div>
              </div>
              <div style={{ color: '#94a3b8' }}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6"/></svg>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
